"""empty message

Revision ID: 1169ddd19aa
Revises: 253d34c2d09
Create Date: 2015-12-20 18:38:49.506196

"""

# revision identifiers, used by Alembic.
revision = '1169ddd19aa'
down_revision = '2751777b30e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('slug', sa.String(length=160), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'slug')
    ### end Alembic commands ###
