"""empty message

Revision ID: 1f872d11bbf
Revises: e07abccfa1
Create Date: 2016-01-08 17:14:46.263330

"""

# revision identifiers, used by Alembic.
revision = '1f872d11bbf'
down_revision = 'e07abccfa1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setting')
    ### end Alembic commands ###
