"""empty message

Revision ID: 1f9c61031fa
Revises: 1f872d11bbf
Create Date: 2016-01-24 17:46:54.879784

"""

# revision identifiers, used by Alembic.
revision = '1f9c61031fa'
down_revision = '1f872d11bbf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('setting', sa.Column('key', sa.String(length=100)))
    op.alter_column('setting', 'name',
        existing_type=sa.VARCHAR(length=100),
        nullable=True) 
    op.drop_column('setting', 'id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('setting', sa.Column('id', sa.INTEGER(), nullable=False))
    op.alter_column('setting', 'name',
        existing_type=sa.VARCHAR(length=100),
        nullable=False)   
    op.drop_column('setting', 'key')
    ### end Alembic commands ###
