"""empty message

Revision ID: 45a63121d32
Revises: 1f872d11bbf
Create Date: 2016-01-18 18:05:23.895923

"""

# revision identifiers, used by Alembic.
revision = '45a63121d32'
down_revision = '1f872d11bbf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=255), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    ### end Alembic commands ###
