"""empty message

Revision ID: 48df0aff185
Revises: 127b78fa140
Create Date: 2015-12-24 17:15:57.080430

"""

# revision identifiers, used by Alembic.
revision = '48df0aff185'
down_revision = '127b78fa140'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'user', ['post_id'], ['id'])
    op.drop_column('post', 'author')
    op.drop_constraint('tags_posts_tag_id_fkey', 'tags_posts', type_='foreignkey')
    op.drop_constraint('tags_posts_post_id_fkey', 'tags_posts', type_='foreignkey')
    op.create_foreign_key(None, 'tags_posts', 'post', ['post_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'tags_posts', 'tag', ['tag_id'], ['id'], ondelete='cascade')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags_posts', type_='foreignkey')
    op.drop_constraint(None, 'tags_posts', type_='foreignkey')
    op.create_foreign_key('tags_posts_post_id_fkey', 'tags_posts', 'post', ['post_id'], ['id'])
    op.create_foreign_key('tags_posts_tag_id_fkey', 'tags_posts', 'tag', ['tag_id'], ['id'])
    op.add_column('post', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'post_id')
    ### end Alembic commands ###
