"""empty message

Revision ID: 50fcee1753d
Revises: 2c579199005
Create Date: 2016-01-26 17:59:25.021819

"""

# revision identifiers, used by Alembic.
revision = '50fcee1753d'
down_revision = '2c579199005'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('slug', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'slug')
    ### end Alembic commands ###
