"""empty message

Revision ID: e07abccfa1
Revises: 3890f70717a
Create Date: 2015-12-27 16:08:09.859981

"""

# revision identifiers, used by Alembic.
revision = 'e07abccfa1'
down_revision = '3890f70717a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('tag', 'name',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('tag', 'slug',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tag', 'slug',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('tag', 'name',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('role', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    ### end Alembic commands ###
